name: deploy-infrastructure-website

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'

env:
    ENVIRONMENT: prod
    AZURE_RESOURCEGROUP_NAME: rg-dbapp
    AZURE_WEBAPP_NAME: webapp-dbapp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/main.bicep
        parameters: environmentType=${{ env.ENVIRONMENT }},adminUser=${{ secrets.POSTGRES_ADMIN  }},adminPassword=${{ secrets.POSTGRES_PASSWORD  }}